name: "Deploy Proxy Document"

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "47 2 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'v2fly/v2fly-github-io'
          fetch-depth: 1

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        run: |
          if [[ ! -e "$HOME/.ssh" ]]; then
            mkdir -p "$HOME/.ssh" && mkdir 700 "$HOME/.ssh" ;
          fi
          echo "${{ secrets.DEPLOY_SSH_KEY_FOR_PROXY_SHKITS_COM }}" > $HOME/.ssh/id_ed25519_deploy_proxy_document ;
          chmod 600 $HOME/.ssh/id_ed25519_deploy_proxy_document ;
          cd docs/.vuepress/ && mv dist proxy-doc;
          tar -Jcvf proxy-doc.tar.xz proxy-doc;
          scp -P 36000 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=tools -i $HOME/.ssh/id_ed25519_deploy_proxy_document proxy-doc.tar.xz tools@proxy-doc.shkits.com:/home/website/ ;
          ssh -p 36000 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=tools -i $HOME/.ssh/id_ed25519_deploy_proxy_document tools@proxy-doc.shkits.com "cd /home/website/; if [[ -e proxy-doc.bak ]]; then rm -rf proxy-doc.bak ; fi; if [[ -e proxy-doc ]]; then mv proxy-doc proxy-doc.bak ; fi; tar -axvf proxy-doc.tar.xz && ./restart-nginx-pod.sh" ;
